version: "2"
linters:
  default: none
  enable:
    - govet
    - misspell
    - revive
    - unused
    - whitespace
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    paths:
      - .github
      - hack
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - .github
      - hack
      - vendor
      - third_party$
      - builtin$
      - examples$
